version: 2
jobs:
  build:
    docker:
      - image: node:10.15.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Build
          command: npm run build

      - run:
          name: Check dist
          command: ls -la dist

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install Firebase-tools
          command: npm install -g firebase-tools

      - run:
          name: Deploy to Firebase hosting
          command: firebase deploy --project "$FIREBASE_ID" --token "$FIREBASE_TOKEN"
